---
title: "Line Graph"
author: "MF"
date: "3/25/2022"
output: html_document
---

# Load library 
```{r}
library(ggplot2)
```
# Code for making clean graph
```{r}
cleanup = theme(panel.grid.major = element_blank(),
                panel.grid.minor = element_blank(),
                panel.background = element_blank(),
                legend.key = element_rect(fill = "white"),
                axis.line = element_line("black"))
```

# Main effect plots          
```{r}
tiff("FigureName.tiff", units="in", width=6, height=4, res=600) #Save the graph as a .tiff file; you can set width, height, and resolution of the image
                                                                #You must include the command line "dev,off()" at the end to successfully save the image 
line = ggplot(LongFormatDatasetName, aes(IV, DV)) #Make a plot with long formatted data (i.e., Each IV and DV is in their own column)
line+
  stat_summary(fun = mean,      #get means
               geom = "point",  #graph points
               na.rm = T)+      #NAs are removed (not taken into computation) if there's any of them
  stat_summary(fun = mean,
               geom = "line",   #graph lines
               na.rm = T,
               aes(group = 1))+
  stat_summary(fun.data = mean_cl_normal,  #get 95% Confidence Intervals; you can also set other kinds of error bars 
               geom = "errorbar", #graph error bars
               na.rm = T,
               width = .1)+
  labs(title = "GRAPH TITLE")+
  xlab("IV NAME")+ #X_axis name
  ylab("DV NAME")+ #y_axis name
  theme(plot.title = element_text(hjust = 0.5), #title position; hjust = horizontal justification & vjust = vertical justification; 0 = left adjusted, 1 = right adjusted, 0.5 is centered 
        title = element_text(color = "black",size = 12,family = "Times New Roman"), #adjust font size, color, etc.
        axis.text= element_text(color = "black",size=14, family = "Times New Roman"),
        axis.title = element_text(color = "black",size = 14, family = "Times New Roman"),
        legend.text = element_text(color = "black",size = 14, family = "Times New Roman"))+
  cleanup #clean up the graph
dev.off() 
#ggsave("FigureName.png", dpi=1200, height=4, width=5, units="in") #Another way to save the image 
                                                                  #comment out tiff() & dev.off() if choose to save images in this way
```
#2-way interaction plots
```{r}
#1. Groups differ by line type (dotted line, dashed line, solid line, etc.)
tiff("FigureName.tiff", units="in", width=5, height=4, res=1200) #Save the graph as a .tiff file; you can set width, height, and resolution of the image
                                                                #You must include the command line "dev,off()" at the end to successfully save the image 
line = ggplot(LongFormatDatasetName, aes(x = IV1, y = DV, linetype = IV2)) #IV2 groups differ by line type
line+
  stat_summary(fun = mean,      #get means
               geom = "point",  #graph points
               na.rm = T)+      #NAs are removed (not taken into computation) if there's any
  stat_summary(fun = mean,
               geom = "line",   #graph lines
               na.rm = T,
               aes(group = IV2))+
  stat_summary(fun.data = mean_cl_normal,  #get 95% Confidence Intervals; you can also set other kinds of error bars  
               geom = "errorbar", #graph error bars
               na.rm = T,
               width = .1)+
  labs(title = "GRAPH TITLE")+
  xlab("IV1 NAME")+ #set X_axis name
  ylab("DV NAME")+  #set y_axis name
  scale_linetype_discrete(name = "IV2 NAME", #set legend name
                          labels = c("IV2_GROUP1", "IV2_GROUP2"))+ #set legend labels (IV2 group names)
  #facet_wrap( ~ IV3)+ #if 3-way interaction
  theme(plot.title = element_text(hjust = 0.5), #title position; hjust = horizontal justification & vjust = vertical justification; 0 = left adjusted, 1 = right adjusted, 0.5 is centered 
        title = element_text(color = "black",size = 12,family = "Times New Roman"),
        axis.text= element_text(color = "black",size=10, family = "Times New Roman"),
        axis.title = element_text(color = "black",size = 12, family = "Times New Roman"),
        legend.text = element_text(color = "black",size = 12, family = "Times New Roman"))+
  cleanup
dev.off()
#ggsave("FigureName.png", dpi=1200, height=4, width=5, units="in") #Another way to save the image 
                                                                  #Comment out tiff() & dev.off() if choose to save images in this way


#2. Groups differ by line color 
tiff("FigureName.tiff", units="in", width=6, height=4, res=600) #Save the graph as a .tiff file; you can set width, height, and resolution of the image
line = ggplot(LongFormatDatasetName, aes(x = IV1, y = DV, color = IV2)) #IV2 groups differ by color
line+
  stat_summary(fun = mean,      #get means
               geom = "point",  #graph points
               na.rm = T)+      #NAs are removed (not taken into computation) if there's any
  stat_summary(fun = mean,
               geom = "line",   #graph lines
               na.rm = T,
               aes(group = IV2),
               size = 1)+
  stat_summary(fun.data = mean_cl_normal,  #get 95% Confidence Intervals; you can also set other kinds of error bars  
               geom = "errorbar", #graph error bars
               na.rm = T,
               width = 0.1,
               size = 0.5)+
  labs(title = "GRAPH TITLE")+
  xlab("IV1 NAME")+ #set X_axis name
  ylab("DV NAME")+  #set y_axis name
  scale_color_brewer(name = "IV2 NAME", #set legend name
                     labels = c("IV2_GROUP1", "IV2_GROUP2"), #set legend labels (IV2 group names)
                     palette="Paired")+ #Select color palette
                                        #Use library("RColorBrewer") & display.brewer.all() to see all palette names
  #facet_wrap( ~ IV3)+ #if 3-way interaction
  theme(plot.title = element_text(hjust = 0.5), #title position; hjust = horizontal justification & vjust = vertical justification; 0 = left adjusted, 1 = right adjusted, 0.5 is centered ,
        title = element_text(color = "black",size = 12,family = "Times New Roman"),
        axis.text= element_text(color = "black",size=14),
        axis.title = element_text(color = "black",size = 14,family = "Times New Roman"),
        legend.text = element_text(color = "black",size = 14,family = "Times New Roman"),
        legend.position="bottom")+ #set legend position; can change it to other places (top, right, left, etc.)
  cleanup
dev.off()
#ggsave("FigureName.png", dpi=1200, height=4, width=5, units="in") #Another way to save the image 
                                                                   #Comment out tiff() & dev.off() if choose to save images in this way
```
